// Données des jeux à deux.

export const QUI_PROMPTS: string[] = [
  'Qui est le plus jaloux·se ?',
  'Qui dit le plus souvent « je t’aime » ?',
  'Qui se réveille le plus tôt ?',
  'Qui est le·la plus tête en l’air ?',
  'Qui cuisine le mieux ?',
  'Qui est le·la plus romantique ?',
  'Qui rit le plus fort ?',
  'Qui craque le premier après une dispute ?',
  'Qui prend le plus de temps à se préparer ?',
  'Qui est le·la plus gourmand·e ?',
  'Qui envoie le plus de messages ?',
  'Qui est le·la plus organisé·e ?',
  'Qui ronfle ? 😴',
  'Qui a le pire sens de l’orientation ?',
  'Qui dépense le plus ?',
  'Qui est le·la plus tactile ?',
  'Qui choisit le film le plus souvent ?',
  'Qui est le·la plus rancunier·e ?',
  'Qui pleure devant les films ?',
  'Qui a dit « je t’aime » en premier ?',
  'Qui est le·la plus aventureux·se ?',
  'Qui garde le plus son calme ?',
];

export const KNOW_QUESTIONS: string[] = [
  'Le plat que je pourrais manger tous les jours ?',
  'Ma plus grande peur ?',
  'Mon film ou ma série préféré·e du moment ?',
  'Mon endroit de rêve pour des vacances ?',
  'Ma manière préférée de me détendre ?',
  'Ce qui me met de bonne humeur à coup sûr ?',
  'Mon plus beau souvenir d’enfance ?',
  'Ce qui m’agace le plus ?',
  'Mon petit plaisir coupable ?',
  'La chanson qui me fait toujours danser ?',
  'Mon rêve un peu fou ?',
  'Ce dont je suis le·la plus fier·e ?',
];

// Les 36 questions (version condensée, 3 séries).
export const Q36_QUESTIONS: string[] = [
  'Si tu pouvais inviter n’importe qui à dîner, qui choisirais-tu ?',
  'Aimerais-tu être célèbre ? De quelle manière ?',
  'Avant de téléphoner, répètes-tu ce que tu vas dire ? Pourquoi ?',
  'Pour toi, à quoi ressemblerait une journée « parfaite » ?',
  'Quand as-tu chanté pour la dernière fois, seul·e ? Et devant quelqu’un ?',
  'Si tu pouvais vivre jusqu’à 90 ans en gardant l’esprit ou le corps d’un·e trentenaire, lequel choisirais-tu ?',
  'As-tu une intuition secrète sur la façon dont tu mourras ?',
  'Nomme trois choses que nous semblons avoir en commun.',
  'Pour quoi dans ta vie ressens-tu le plus de gratitude ?',
  'Si tu pouvais changer une chose dans ta façon d’avoir été élevé·e, laquelle ?',
  'En 4 minutes, raconte-moi l’histoire de ta vie le plus en détail possible.',
  'Si tu pouvais te réveiller demain avec une nouvelle qualité, laquelle ?',
  'Qu’aimerais-tu savoir sur ton avenir ?',
  'Y a-t-il quelque chose que tu rêves de faire depuis longtemps ? Pourquoi ne l’as-tu pas fait ?',
  'Quel est le plus grand accomplissement de ta vie ?',
  'Qu’est-ce que tu valorises le plus dans une amitié ?',
  'Quel est ton souvenir le plus précieux ?',
  'Quel est ton souvenir le plus terrible ?',
  'Si tu savais que tu allais mourir dans un an, changerais-tu ta façon de vivre ?',
  'Que représente l’amitié pour toi ?',
  'Quel rôle jouent l’amour et l’affection dans ta vie ?',
  'Dis une qualité que tu apprécies déjà chez moi.',
  'À quel point ta famille est-elle proche et chaleureuse ?',
  'Comment ressens-tu ta relation avec ta mère ?',
  'Fais trois phrases commençant par « nous » qui décrivent ce moment.',
  'Complète : « J’aimerais partager avec quelqu’un… »',
  'Que devrais-je savoir de toi pour devenir un·e ami·e proche ?',
  'Dis-moi ce que tu aimes chez moi, sincèrement.',
  'Partage un moment gênant de ta vie.',
  'Quand as-tu pleuré pour la dernière fois devant quelqu’un ? Seul·e ?',
  'Dis-moi une chose que tu aimes déjà chez moi.',
  'Qu’est-ce qui est trop sérieux pour être tourné en dérision ?',
  'Si tu devais mourir ce soir sans pouvoir parler à personne, que regretterais-tu de n’avoir jamais dit ?',
  'Ta maison brûle. Après les proches, quel objet sauverais-tu ?',
  'De tous les membres de ta famille, quelle mort te bouleverserait le plus ?',
  'Partage un problème personnel et demande-moi comment je le gérerais.',
];
